name: otrujja
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  flutter_native_splash: ^0.1.9
  webview_flutter: ^0.3.22+1
  flutter_launcher_icons: ^0.7.5

flutter_native_splash:
  image: assets/otruja.png
  color: "000000"
  fill: true
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/otruja.png"

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true
assets:
  - assets/
  