name: otrujja
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_inappwebview: ^5.3.2
  flutter_launcher_icons: ^0.9.1
  permission_handler: ^8.1.4+2
  url_launcher: ^6.0.9

flutter_native_splash:
  image: assets/otruja.png
  color: "000000"
  fill: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/otruja.png"

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
assets:
  - assets/

fonts:
  family: "tajawal"
  fonts:
    - assets/Fonts/Tajawal-Regular.ttf
