name: otrujja
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_web_view: ^1.2.0
  flutter_native_splash: ^0.1.9
  webview_flutter: ^0.3.22+1

flutter_native_splash:
  image: assets/otruja.png
  color: "000000"
  fill: true
  
  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true
assets:
  - assets/
  